services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tpsu
      POSTGRES_PASSWORD: 2305
      POSTGRES_DB: TourPlanner
    ports:
      - 5432:5432
  
  tour-planner:
    restart: unless-stopped
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
